.\" Manuálová stránka pro gnuClassConf.
.\" Kontaktujte beranm14@fit.cvut.cz pro opravu chyb a gramatických chyb.
.TH man 1 "11 DEC 2013" "0.001" "gnuClassConf manuálová stránka"
.SH NAME
gnuClassConf \- Ovládání třídy v rámci LAN
.SH SYNOPSIS
.B gnuClassConf
.SH DESCRIPTION
gnuClassConf je aplikace pro správu učebny v rámci sítě LAN. Umožňuje instalovat třídu, aplikace pro třídu, sdílet složky pro studenty, ...
.SH OPTIONS
Skripty gnuClassConf obsahují přepínače, ale ne spouštějící skript.
.SH BUGS
Zatím žádné známé, oznamnte je autorovi hned, jak na ně přijdete.
.SH AUTHOR
Martin Beránek(beranm14@fit.cvut.cz)
