#!/bin/bash
# Uninstalace aplikace
#
# Cílová složka
# Test interaktivity
if [[ $DEBIAN_FRONTEND != "noninteractive" ]]; then
	TDIR="/opt/gnuClassConf";
	# optání se, zdali je má vrátit do původního stavu
	bck="/etc/network/interfaces_ducked_back";
	if [[ -r "$bck" ]];then
		echo "Konfigurační prostředí zálohovalo soubor";
		echo "/etc/network/interfaces, má se vrátit";
		echo "do původního stavu?"
		read -p "Zvolte (a) pro vrácení, (n) pro smazání: " y
		y=${y:-n}
		if [[ "$y" == "a" ]];then
			cat /etc/network/interfaces_ducked_back > /etc/network/interfaces;
		fi
		rm "$bck";
	fi
	# Odstranění balíčků
	#echo "Odstraňuji balíčky, které prostředí nainstalovalo";
	# optání se, zdali se maj purgnout
	#echo "Konfigurační prostředí nainstalovalo služby, které potřebuje pro svou činnost.";
	#echo "Mají se také s odinstalací odsranit?";
	#read -p "Zvolte (a) pro odstranění (p) pro odstranění i s konfiguračními soubory, (n) pro nic: " y
	#y=${y:-n}
	#if [[ "$y" == "a" ]];then
	#	apt-get remove isc-dhcp-server tftpd-hpa apache2 nfs-kernel-server tftpd-hpa syslinux debootstrap expect;
	#elif [[ "$y" == "p" ]];then
	#	apt-get remove --purge isc-dhcp-server tftpd-hpa apache2 nfs-kernel-server tftpd-hpa syslinux debootstrap expect;
	#fi
	# Mazání DHCP configuračního souboru
	if [[ -f "/etc/dhcp/class.conf" ]];then
		rm /etc/dhcp/class.conf;
		tm=`mktemp`;
		while read -r line;do
			if [[ $line != "include \"/etc/dhcp/class.conf\";" ]] && [[ $line != "# DUCKED changed" ]];then
				echo $line >> $tm;
			fi
		done < "/etc/dhcp/dhcpd.conf";
		cat $tm > "/etc/dhcp/dhcpd.conf";
		rm $tm;
		service isc-dhcp-server restart;
	fi
	# Mazání exports NFS
	if [[ -f "/etc/exports" ]];then
		tm=`mktemp`;
		while read -r line;do
			if [[ $line != "/NFSROOT/class *(rw,crossmnt,sync,no_root_squash,no_subtree_check)" ]] && [[ $line != "# DUCKED changed" ]];then
				echo $line >> $tm;
			fi
		done < "/etc/exports";
		cat $tm > "/etc/exports";
		rm $tm;
		service nfs-common restart;
		service nfs-kernel-server  restart;
	fi
	# Mazání TFTP serveru
	if [[ -f /srv/tftp/pxelinux.0 ]];then
		rm /srv/tftp/initrd*;
		rm /srv/tftp/vmlinuz-*;
		rm -r /srv/tftp/pxelinux.cfg;
		rm /srv/tftp/pxelinux.0;
		service tftpd-hpa restart;
	fi
	# Mazání obrazu
	if [[ -d "/NFSROOT/" ]]; then
		echo "Při správě učebny bylo potřeba pracovat se složkou obsahující soubory pro třídu";
		echo "Mají se také s odinstalací odstranit?";
		read -p "Zvolte (a) pro odstranění, (n) pro nic: " y
		if [[ "$y" == "a" ]];then
			rm -r "/NFSROOT";
		fi
	fi
fi
exit 0;
