#!/bin/bash
# Instalace aplikace
# Cílová složka
TDIR="/opt/gnuClassConf";
if [[ -d "$TDIR" ]];then
	# Složka už existuje, kopíruji vše až na konfigurační soubory
	# Pokud konfigurační soubory focus/installed.cfg, configuration/shared
	# a configuration/interfaces existují, nepřepisovat
	d="/tmp/gnuClI";
	mkdir $d;
	echo "Zálohuji konfiguraci";
	t="$TDIR/configuration/interfaces";
	[[ -f $t ]] && mv $t $d;
	t="$TDIR/configuration/shared";
	[[ -f $t ]] && mv $t $d;
	t="$TDIR/focus/installed.cfg";
	[[ -f $t ]] && mv $t $d;
fi
